export const validateInputNumber = (input: string) => {
  const num = input.replace(/\s/g, '');
  return (/^\d+$/.test(num))
}

export const formatter = new Intl.NumberFormat('en-US', {
  minimumFractionDigits: 0,
  maximumFractionDigits: 2,
  currency: "USD",
  style: "currency"
})
export const CSS_HANDLES = [
  "container",
  "input_price",
  "container_input",
  "input_text",
  "input",
  "container_price",
  "text_price",
  "text_price_box",
  "content_modal_met",
  "content_modal_met_text",
  "text_price_price",
  "text_price_mount",
  "text_price_price_top",
  "input_radius",
  "radius_input",
  "radius_text",
  "radius_label",
  "content_modal_why",
  "content_modal_why_text",
  "box_price",
  "box_content",
  "box_content_text",
  "box_content_text_box",
  "content_price",
  "price",
  "price_text",
  "box_total_price",
  "total_price_text",
  "total_price_amount",
  "total_price_text_b",
  "box_btn",
  "btn_content",
  "btn_img_list",
  "btn_img",
  "btn_free",
  "btn_free_content",
  "free_content_text",
  "content_text_free",
  "content_text_pay",
  "content_add_img_text",
  "content_add_img",
  "content_add_text",
  "btn_add",
  "btn_add_content",
  "btn_add_text",
  "btn_addcart",
  "btn_addcart_content",
  "btn_addcart_text",
  "box_additional",
  "Modal__content",
  "Modal__content_modal",
  "content_modal_content",
  "modal_content_close",
  "modal_close",
  "container_glue",
  "glue_img",
  "glue_name",
  "glue_value_text",
  "glue_value",
  "glue_content_select",
  "glue_btn_less",
  "glue_btn_count",
  "glue_btn_more",
  "glue_content_total",
  "glue_total_text",
  "glue_total",
  "glue_value_content",
  "modal_open",
  "img1_modal",
  "img2_modal",
  "img3_modal",
  "img4_modal",
  "content_modal_why_open",
  "content_modal_why_open_text",
  "glue_input_checkbox",
  "btn_buy_whatsapp",
  "btn_add_content_whatsapp",
  "btn_add_text_whatsapp",
  "btn_img_whatsapp",
  "btn_buy_sample",
  "containercalc",
  "columncalc",
  "btn_quote",
  "btn_quote_list",
  "title_area_quote"
]